# Generated by Django 3.2.21 on 2023-10-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231018_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/assets/images/default.jpg', upload_to='profile-picture'),
        ),
    ]
