# Generated by Django 3.2.21 on 2024-01-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20231030_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
