# Generated by Django 3.2.21 on 2023-10-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turtles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='turtles')),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
