# Generated by Django 3.2.21 on 2023-10-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('turtles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtles',
            name='sponsor',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
