# Generated by Django 3.2.21 on 2023-10-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231018_1723'),
        ('turtles', '0002_alter_turtles_sponsor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turtles',
            new_name='Turtle',
        ),
    ]
