# Generated by Django 3.2.21 on 2023-10-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turtles', '0003_rename_turtles_turtle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turtle',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='turtle',
            name='status',
        ),
    ]
