# Generated by Django 3.2.21 on 2023-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtles', '0004_auto_20231025_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtle',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turtle',
            name='discovery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='turtle',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='turtle',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='turtle',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
