# Generated by Django 3.2.21 on 2024-03-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_alter_review_rating'),
        ('checkout', '0004_order_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='review',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchandise.review'),
        ),
    ]
