# Generated by Django 3.2.21 on 2024-03-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20240309_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='review',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
