# Generated by Django 3.2.21 on 2024-03-07 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donations',
            new_name='donation',
        ),
    ]
