# Generated by Django 3.2.21 on 2023-11-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20231101_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
