# Generated by Django 3.2.21 on 2024-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0005_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, null=True),
        ),
    ]
